### ISSUE TITLE
Error: Global symbol "$settings" requires explicit package name at line 216

### ISSUE THREAD

**Issue by adeuxdev2** [PerlDancer/Dancer2-Plugin-Auth-Extensible-Provider-LDAP#1]
Hi,
Using strict
I cannot get Dancer2 to compile this module as $settings in line 216 is undeclared:

215     if (@roles == 0) {
216        $self->plugin->app->warning($settings->{roles});
217    }

I am nor sure what this is doing - It seems like it should be a warning like the lines above eg:

$self->plugin->app->warning($mesg->error);

**Comment by SysPete** [comment]
Hi @adeuxdev2.

Current LDAP provider is broken and I'm working on a new version. Will ping here when it is uploaded.

**Comment by SysPete** [comment]
Latest release v0.700 has been release to CPAN with this issue fixed.
