### ISSUE TITLE
Authentication Types

### ISSUE THREAD

**Issue by niconil** [PerlDancer/Dancer2-Plugin-Auth-Extensible-Provider-LDAP#3]
i'm a kanboard user

in this application i can choose to authenticate against an external LDAP Directory
this application have three modes (anonymous, proxy user, user) below the link to the documentation page
https://kanboard.net/documentation/ldap-authentication

i would like to do the same with Dancer2-Plugin-Auth-Extensible-Provider-LDAP
with the equivalent of the user mode

is it possible to do that ? when i read your doc i understand you have implemented the mode designated by "proxy user" in kanboard documentation, but i have no such credentials.

**Comment by SysPete** [comment]
Hi @niconil 

Yes: currently the provider requires bind credentials in order to operate. Having the option for anonymous bind would be pretty simple to add but I need to have a think about "user" style as per kanboard due to the way `get_user_details` currently works.

**Comment by niconil** [comment]
yes i'm interesting by "user" mode ....

if i can help you ...
in kanboard the code is here (in PHP) : 
https://github.com/kanboard/kanboard/blob/master/app/Auth/LdapAuth.php

disussion suggesting the actual 3 modes is here
https://github.com/kanboard/kanboard/issues/4#issuecomment-52684372
and few following comments

i understand your preference to "think" before "code"
thanks for your first answer

**Comment by niconil** [comment]
some news ?

**Comment by niconil** [comment]
hello
what can i do about this issue ?

**Comment by bigpresh** [comment]
If you're keen, you could always try implementing support for anonymous bind mode and raising a PR :)

**Comment by SysPete** [comment]
anonymous bind mode is now support following merge of #6

**Comment by SysPete** [comment]
closed via #6
